# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addvitals.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.btnInsert = QtWidgets.QPushButton(Form)
        self.btnInsert.setGeometry(QtCore.QRect(0, 430, 84, 39))
        self.btnInsert.setObjectName("btnInsert")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(121, 11, 341, 452))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lbltime = QtWidgets.QLabel(self.layoutWidget)
        self.lbltime.setObjectName("lbltime")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbltime)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 5, 27), QtCore.QTime(12, 0, 0)))
        self.dateTimeEdit.setDate(QtCore.QDate(2021, 5, 27))
        self.dateTimeEdit.setTime(QtCore.QTime(12, 0, 0))
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateTimeEdit)
        self.syslabel = QtWidgets.QLabel(self.layoutWidget)
        self.syslabel.setObjectName("syslabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.syslabel)
        self.cmbsystolic = QtWidgets.QComboBox(self.layoutWidget)
        self.cmbsystolic.setEditable(True)
        self.cmbsystolic.setObjectName("cmbsystolic")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmbsystolic)
        self.lbldiastolic = QtWidgets.QLabel(self.layoutWidget)
        self.lbldiastolic.setObjectName("lbldiastolic")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbldiastolic)
        self.cmbdiastolic = QtWidgets.QComboBox(self.layoutWidget)
        self.cmbdiastolic.setEditable(True)
        self.cmbdiastolic.setObjectName("cmbdiastolic")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmbdiastolic)
        self.lblheartrate = QtWidgets.QLabel(self.layoutWidget)
        self.lblheartrate.setObjectName("lblheartrate")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblheartrate)
        self.cmbheartrate = QtWidgets.QComboBox(self.layoutWidget)
        self.cmbheartrate.setEditable(True)
        self.cmbheartrate.setObjectName("cmbheartrate")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cmbheartrate)
        self.lblsugar = QtWidgets.QLabel(self.layoutWidget)
        self.lblsugar.setObjectName("lblsugar")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblsugar)
        self.cmbsugar = QtWidgets.QComboBox(self.layoutWidget)
        self.cmbsugar.setEditable(True)
        self.cmbsugar.setObjectName("cmbsugar")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cmbsugar)
        self.lbloxy = QtWidgets.QLabel(self.layoutWidget)
        self.lbloxy.setObjectName("lbloxy")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbloxy)
        self.cmboxy = QtWidgets.QComboBox(self.layoutWidget)
        self.cmboxy.setEditable(True)
        self.cmboxy.setObjectName("cmboxy")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cmboxy)
        self.lblcomment = QtWidgets.QLabel(self.layoutWidget)
        self.lblcomment.setObjectName("lblcomment")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lblcomment)
        self.lncomment = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.lncomment.setObjectName("lncomment")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lncomment)
        self.btnExit = QtWidgets.QPushButton(Form)
        self.btnExit.setGeometry(QtCore.QRect(520, 430, 105, 39))
        self.btnExit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btnExit.setObjectName("btnExit")
        self.lblInsert = QtWidgets.QLabel(Form)
        self.lblInsert.setGeometry(QtCore.QRect(10, 380, 101, 23))
        self.lblInsert.setObjectName("lblInsert")
        self.lbltime.setBuddy(self.dateTimeEdit)
        self.syslabel.setBuddy(self.cmbsystolic)
        self.lbldiastolic.setBuddy(self.cmbdiastolic)
        self.lblheartrate.setBuddy(self.cmbheartrate)
        self.lblsugar.setBuddy(self.cmbsugar)
        self.lbloxy.setBuddy(self.cmboxy)
        self.lblcomment.setBuddy(self.lncomment)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.dateTimeEdit, self.cmbsystolic)
        Form.setTabOrder(self.cmbsystolic, self.cmbdiastolic)
        Form.setTabOrder(self.cmbdiastolic, self.cmbheartrate)
        Form.setTabOrder(self.cmbheartrate, self.cmbsugar)
        Form.setTabOrder(self.cmbsugar, self.cmboxy)
        Form.setTabOrder(self.cmboxy, self.lncomment)
        Form.setTabOrder(self.lncomment, self.btnInsert)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnInsert.setText(_translate("Form", "&Insert"))
        self.lbltime.setText(_translate("Form", "Date Time"))
        self.dateTimeEdit.setDisplayFormat(_translate("Form", "M/d/yy HH:mm"))
        self.syslabel.setText(_translate("Form", "Systolic"))
        self.lbldiastolic.setText(_translate("Form", "Diastolic"))
        self.lblheartrate.setText(_translate("Form", "Heart rate"))
        self.lblsugar.setText(_translate("Form", "Sugar"))
        self.lbloxy.setText(_translate("Form", "O2"))
        self.lblcomment.setText(_translate("Form", "Comment"))
        self.btnExit.setText(_translate("Form", "E&xit"))
        self.lblInsert.setText(_translate("Form", "Insert Only"))
