# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './notes.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Comment(object):
    def setupUi(self, Comment):
        Comment.setObjectName("Comment")
        Comment.resize(827, 632)
        self.gridLayout = QtWidgets.QGridLayout(Comment)
        self.gridLayout.setObjectName("gridLayout")
        self.lblBSrecord = QtWidgets.QLabel(Comment)
        self.lblBSrecord.setObjectName("lblBSrecord")
        self.gridLayout.addWidget(self.lblBSrecord, 0, 0, 1, 1)
        self.spinBsid = QtWidgets.QSpinBox(Comment)
        self.spinBsid.setMaximum(9999)
        self.spinBsid.setObjectName("spinBsid")
        self.gridLayout.addWidget(self.spinBsid, 0, 1, 1, 1)
        self.lblBPrecord = QtWidgets.QLabel(Comment)
        self.lblBPrecord.setObjectName("lblBPrecord")
        self.gridLayout.addWidget(self.lblBPrecord, 0, 3, 1, 1)
        self.spinBpid = QtWidgets.QSpinBox(Comment)
        self.spinBpid.setMaximum(9999)
        self.spinBpid.setObjectName("spinBpid")
        self.gridLayout.addWidget(self.spinBpid, 0, 4, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(Comment)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout.addWidget(self.dateTimeEdit, 1, 0, 1, 1)
        self.lblLastRecord = QtWidgets.QLabel(Comment)
        self.lblLastRecord.setObjectName("lblLastRecord")
        self.gridLayout.addWidget(self.lblLastRecord, 2, 0, 1, 2)
        self.lblRecord1 = QtWidgets.QLabel(Comment)
        self.lblRecord1.setObjectName("lblRecord1")
        self.gridLayout.addWidget(self.lblRecord1, 2, 2, 1, 1)
        self.tblPrevRec = QtWidgets.QTableView(Comment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.tblPrevRec.sizePolicy().hasHeightForWidth())
        self.tblPrevRec.setSizePolicy(sizePolicy)
        self.tblPrevRec.setObjectName("tblPrevRec")
        self.gridLayout.addWidget(self.tblPrevRec, 3, 0, 1, 5)
        self.textEdit = QtWidgets.QTextEdit(Comment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(75)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 4, 0, 1, 5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnExit = QtWidgets.QPushButton(Comment)
        self.btnExit.setObjectName("btnExit")
        self.horizontalLayout.addWidget(self.btnExit)
        self.btnUpdate = QtWidgets.QPushButton(Comment)
        self.btnUpdate.setObjectName("btnUpdate")
        self.horizontalLayout.addWidget(self.btnUpdate)
        self.btnAdd = QtWidgets.QPushButton(Comment)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout.addWidget(self.btnAdd)
        self.chkPG = QtWidgets.QCheckBox(Comment)
        self.chkPG.setObjectName("chkPG")
        self.horizontalLayout.addWidget(self.chkPG)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 3)
        self.lblRecord2 = QtWidgets.QLabel(Comment)
        self.lblRecord2.setObjectName("lblRecord2")
        self.gridLayout.addWidget(self.lblRecord2, 2, 3, 1, 1)
        self.lblBSrecord.setBuddy(self.spinBsid)
        self.lblBPrecord.setBuddy(self.spinBpid)
        self.lblLastRecord.setBuddy(self.tblPrevRec)

        self.retranslateUi(Comment)
        QtCore.QMetaObject.connectSlotsByName(Comment)

    def retranslateUi(self, Comment):
        _translate = QtCore.QCoreApplication.translate
        Comment.setWindowTitle(_translate("Comment", "Note"))
        self.lblBSrecord.setText(_translate("Comment", "Last Blood sugar record"))
        self.lblBPrecord.setText(_translate("Comment", "Last Blood pressure record"))
        self.lblLastRecord.setText(_translate("Comment", "<html><head/><body><p>Last record from <span style=\" font-weight:600;\">vsigns_bp</span></p></body></html>"))
        self.lblRecord1.setText(_translate("Comment", "SL"))
        self.btnExit.setText(_translate("Comment", "E&xit"))
        self.btnUpdate.setText(_translate("Comment", "&Update"))
        self.btnAdd.setText(_translate("Comment", "&Add"))
        self.chkPG.setText(_translate("Comment", "Postgres"))
        self.lblRecord2.setText(_translate("Comment", "PG"))
