# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notes.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Comment(object):
    def setupUi(self, Comment):
        Comment.setObjectName("Comment")
        Comment.resize(827, 632)
        self.gridLayout_2 = QtWidgets.QGridLayout(Comment)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(Comment)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout.addWidget(self.dateTimeEdit, 1, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(Comment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tblPrevRec = QtWidgets.QTableView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.tblPrevRec.sizePolicy().hasHeightForWidth())
        self.tblPrevRec.setSizePolicy(sizePolicy)
        self.tblPrevRec.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tblPrevRec.setObjectName("tblPrevRec")
        self.textEdit = QtWidgets.QTextEdit(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(75)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.splitter, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblBSrecord = QtWidgets.QLabel(Comment)
        self.lblBSrecord.setObjectName("lblBSrecord")
        self.horizontalLayout_2.addWidget(self.lblBSrecord)
        self.spinBsid = QtWidgets.QSpinBox(Comment)
        self.spinBsid.setMaximum(9999)
        self.spinBsid.setObjectName("spinBsid")
        self.horizontalLayout_2.addWidget(self.spinBsid)
        self.lblBPrecord = QtWidgets.QLabel(Comment)
        self.lblBPrecord.setObjectName("lblBPrecord")
        self.horizontalLayout_2.addWidget(self.lblBPrecord)
        self.spinBpid = QtWidgets.QSpinBox(Comment)
        self.spinBpid.setMaximum(9999)
        self.spinBpid.setObjectName("spinBpid")
        self.horizontalLayout_2.addWidget(self.spinBpid)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnExit = QtWidgets.QPushButton(Comment)
        self.btnExit.setObjectName("btnExit")
        self.horizontalLayout.addWidget(self.btnExit)
        self.btnUpdate = QtWidgets.QPushButton(Comment)
        self.btnUpdate.setObjectName("btnUpdate")
        self.horizontalLayout.addWidget(self.btnUpdate)
        self.btnAdd = QtWidgets.QPushButton(Comment)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout.addWidget(self.btnAdd)
        self.chkPG = QtWidgets.QCheckBox(Comment)
        self.chkPG.setObjectName("chkPG")
        self.horizontalLayout.addWidget(self.chkPG)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.lblLastRecord = QtWidgets.QLabel(Comment)
        self.lblLastRecord.setObjectName("lblLastRecord")
        self.gridLayout.addWidget(self.lblLastRecord, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.lblBSrecord.setBuddy(self.spinBsid)
        self.lblBPrecord.setBuddy(self.spinBpid)
        self.lblLastRecord.setBuddy(self.tblPrevRec)

        self.retranslateUi(Comment)
        QtCore.QMetaObject.connectSlotsByName(Comment)

    def retranslateUi(self, Comment):
        _translate = QtCore.QCoreApplication.translate
        Comment.setWindowTitle(_translate("Comment", "Note"))
        self.lblBSrecord.setText(_translate("Comment", "Last Blood sugar record"))
        self.lblBPrecord.setText(_translate("Comment", "Last Blood pressure record"))
        self.btnExit.setText(_translate("Comment", "E&xit"))
        self.btnUpdate.setText(_translate("Comment", "&Update"))
        self.btnAdd.setText(_translate("Comment", "&Add"))
        self.chkPG.setText(_translate("Comment", "Postgres"))
        self.lblLastRecord.setText(_translate("Comment", "<html><head/><body><p>Last record from <span style=\" font-weight:600;\">vsigns_bp</span></p></body></html>"))
