# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './sugar.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sugar(object):
    def setupUi(self, Sugar):
        Sugar.setObjectName("Sugar")
        Sugar.resize(1247, 692)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Sugar.sizePolicy().hasHeightForWidth())
        Sugar.setSizePolicy(sizePolicy)
        Sugar.setMaximumSize(QtCore.QSize(1247, 692))
        self.lblLastRec = QtWidgets.QLabel(Sugar)
        self.lblLastRec.setGeometry(QtCore.QRect(10, 160, 95, 21))
        self.lblLastRec.setObjectName("lblLastRec")
        self.tblViewRec = QtWidgets.QTableView(Sugar)
        self.tblViewRec.setGeometry(QtCore.QRect(10, 200, 1231, 471))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblViewRec.sizePolicy().hasHeightForWidth())
        self.tblViewRec.setSizePolicy(sizePolicy)
        self.tblViewRec.setObjectName("tblViewRec")
        self.tblViewRec.horizontalHeader().setDefaultSectionSize(200)
        self.tblViewRec.horizontalHeader().setMinimumSectionSize(50)
        self.tblViewRec.horizontalHeader().setStretchLastSection(True)
        self.tblViewRec.verticalHeader().setDefaultSectionSize(30)
        self.tblViewRec.verticalHeader().setMinimumSectionSize(20)
        self.lblComment = QtWidgets.QLabel(Sugar)
        self.lblComment.setGeometry(QtCore.QRect(10, 8, 209, 21))
        self.lblComment.setObjectName("lblComment")
        self.txtComment = QtWidgets.QPlainTextEdit(Sugar)
        self.txtComment.setGeometry(QtCore.QRect(10, 40, 621, 51))
        self.txtComment.setPlainText("")
        self.txtComment.setObjectName("txtComment")
        self.chkPG = QtWidgets.QCheckBox(Sugar)
        self.chkPG.setGeometry(QtCore.QRect(510, 10, 94, 26))
        self.chkPG.setObjectName("chkPG")
        self.btnInsert = QtWidgets.QPushButton(Sugar)
        self.btnInsert.setGeometry(QtCore.QRect(110, 100, 75, 31))
        self.btnInsert.setObjectName("btnInsert")
        self.sugarCombo = QtWidgets.QComboBox(Sugar)
        self.sugarCombo.setGeometry(QtCore.QRect(200, 100, 93, 27))
        self.sugarCombo.setEditable(True)
        self.sugarCombo.setObjectName("sugarCombo")
        self.lblInsert = QtWidgets.QLabel(Sugar)
        self.lblInsert.setGeometry(QtCore.QRect(310, 10, 121, 21))
        self.lblInsert.setObjectName("lblInsert")
        self.btnExit = QtWidgets.QPushButton(Sugar)
        self.btnExit.setGeometry(QtCore.QRect(20, 100, 75, 31))
        self.btnExit.setObjectName("btnExit")
        self.lblSugar = QtWidgets.QLabel(Sugar)
        self.lblSugar.setGeometry(QtCore.QRect(220, 130, 49, 21))
        self.lblSugar.setObjectName("lblSugar")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(Sugar)
        self.dateTimeEdit.setGeometry(QtCore.QRect(310, 100, 211, 31))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.btnGraph = QtWidgets.QPushButton(Sugar)
        self.btnGraph.setGeometry(QtCore.QRect(550, 100, 151, 31))
        self.btnGraph.setObjectName("btnGraph")
        self.btnGraph_2 = QtWidgets.QPushButton(Sugar)
        self.btnGraph_2.setGeometry(QtCore.QRect(720, 100, 151, 31))
        self.btnGraph_2.setObjectName("btnGraph_2")

        self.retranslateUi(Sugar)
        QtCore.QMetaObject.connectSlotsByName(Sugar)

    def retranslateUi(self, Sugar):
        _translate = QtCore.QCoreApplication.translate
        Sugar.setWindowTitle(_translate("Sugar", "Sugar"))
        self.lblLastRec.setText(_translate("Sugar", "Last Record"))
        self.lblComment.setText(_translate("Sugar", "Comment for new record:"))
        self.chkPG.setText(_translate("Sugar", "Postgres"))
        self.btnInsert.setText(_translate("Sugar", "A&dd"))
        self.lblInsert.setText(_translate("Sugar", "Insert Rec"))
        self.btnExit.setText(_translate("Sugar", "E&xit"))
        self.lblSugar.setText(_translate("Sugar", "Sugar"))
        self.btnGraph.setText(_translate("Sugar", "&Graph 48 hrs"))
        self.btnGraph_2.setText(_translate("Sugar", "&Graph 8 days"))
